title: "Joshua Screen"
description: "Official website of Joshua Screen — Actor, Music Artist, Photographer, and Creative Director."
url: "https://www.jtscreen.com"

author:
  name: "Joshua Screen"
  email: "jtscreen23@gmail.com"  # optional

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Needed for GitHub Pages
markdown: kramdown
theme: minima  # or whatever theme you're using
