plugins:
  - jekyll-seo-tag

# Optional but useful metadata
layout: default
title: "Joshua Screen – Actor, Musician, Photographer"
description: "Official website of Joshua Screen. Portfolio in acting, photography, music, and more."
url: "https://www.jtscreen.com"
author:
  name: "Joshua Screen"
  email: jtscreen23@gmail.com
